[Variables]
Main_FG =FFFFFF
Secondary_FG =E6E6E6
Main_BG =000000
Sidebar_And_Player_BG =000000
Cover_Overlay_And_Shadow =000000
Indicator_FG_And_Button_BG =1DB954
Pressing_FG =189644
Slider_BG =333333
Sidebar_Indicator_And_Hover_Button_BG =1DB954
Scrollbar_FG_And_Selected_Row_BG =333333
Pressing_Button_FG =E6E6E6
Pressing_Button_BG =189644
Selected_Button =1DB954
Miscellaneous_BG =1DB954
Miscellaneous_Hover_BG =189644
Preserve_1 =FFFFFF
